kind: pipeline
name: Deploy

steps:
- name: docker  
  image: plugins/docker
  settings:
    auto_tag: true
    dry_run: false
    dockerfile: Velocloud2Connectwise/Dockerfile
    repo: registry.m5.run/velocloud2connectwise
    registry: registry.m5.run
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: magna5/azuredeploy
  settings:
    azure_appid:
      from_secret: azure_appid
    azure_password:
      from_secret: azure_password
    azure_tenant:
      from_secret: azure_tenant
    resource_group: Servers_Prod_West2
    container_name: vc2cw
    image: registry.m5.run/velocloud2connectwise:${DRONE_SEMVER}
    dns: vc2cw
    ports: 8077
    registry: registry.m5.run
    registry_user:
      from_secret: docker_username
    registry_password:
      from_secret: docker_password

trigger:
  branch:
    - master
  event:
    - tag
